services:
  python:
    build:
      context: ./py
      dockerfile: Dockerfile
    volumes:
      - ./py:/usr/src/app
    init: true
    tty: true
  gcc:
    build:
      context: ./c-lang
      dockerfile: Dock
    volumes:
      - data:/usr/src/
    init: true
    tty: true
volumes:
  data:
    driver: local