services:
  python:
    build:
      context: ./python
      dockerfile: DockFile
    volumes:
      - ./python:/usr/src/app
    tty: true
  c:
    build:
      context: ./c-lang
      dockerfile: dockerfile
    volumes:
      - data:/usr/src/
    tty: true
volumes:
  data:
    driver: local